---
name: "Banabas Kariuki"
title: "Linear Regression Mini-competition"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries
```{r}
library(tidymodels)
library(readxl)
library(dplyr)
library(ggplot2)
```

```{r}
# Load and prepare data
data_2016 <- read_excel("~/Preparations/STA 631/activity08-mini-competition/activity08-mini-competition/competition-files/data/pfi-data.xlsx", sheet = "curated 2016") %>%
  mutate_if(is.character, as.factor) %>%
  mutate(ALLGRADEX = as.factor(ALLGRADEX))

data_2019 <- read_excel("~/Preparations/STA 631/activity08-mini-competition/activity08-mini-competition/competition-files/data/pfi-data.xlsx", sheet = "curated 2019") %>%
  mutate_if(is.character, as.factor) %>%
  mutate(ALLGRADEX = as.factor(ALLGRADEX))
```

```{r}
# Combine datasets
data_combined <- bind_rows(data_2016, data_2019)
```

```{r}
# Preprocess SCCHOICE variable
data_combined <- data_combined %>%
  filter(SCCHOICE != -1) %>%
  mutate(SCCHOICE = factor(SCCHOICE, levels = c(1, 2), labels = c("Yes", "No")))
```


```{r}
# Detailed EDA for each variable group
# Example for school choice variables
school_choice_vars <- c("SPUBCHOIX", "SCONSIDR", "SEGRADES")
family_engagement_vars <- c("FSSPORTX", "FSMTNG", "FSPTMTNG", "FSATCNFN")
homework_vars <- c("FHHOME", "FHCAMT", "FHPLACE")
```

```{r}
# Plotting function
plot_categorical <- function(data, vars) {
  for (var in vars) {
    print(ggplot(data, aes_string(x = var, fill = var)) + 
            geom_bar() + 
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            labs(title = paste("Distribution of", var)))
  }
}

plot_categorical(data_combined, school_choice_vars)
plot_categorical(data_combined, family_engagement_vars)
plot_categorical(data_combined, homework_vars)
```

```{r}
# Splitting the dataset
set.seed(123)
data_split <- initial_split(data_combined, prop = 0.8)
train_data <- training(data_split)
test_data <- testing(data_split)
```
```{r}
# Check levels of all factor variables
sapply(select(train_data, where(is.factor)), function(x) nlevels(x))
```


```{r}
# Model setup
glm_model <- logistic_reg() %>% 
  set_engine("glm") %>%
  set_mode("classification")
```

```{r}
# Recipe with interaction terms
recipe <- recipe(SCCHOICE ~ ., data = train_data) %>%
  step_dummy(all_nominal_predictors(), -all_outcomes()) %>%
  step_interact(terms = ~ SPUBCHOIX:FSSPORTX)
```

```{r}
glm_fit <- workflow() %>%
  add_model(glm_model) %>%
  add_recipe(recipe) %>%
  fit(data = train_data)
```

```{r}
# Setting up resampling with v-fold cross-validation
set.seed(123)
cv_resamples <- vfold_cv(train_data, v = 5)

# Proceed with fitting the model on corrected training data
glm_fit_results <- fit_resamples(
  workflow() %>%
    add_model(glm_model) %>%
    add_recipe(recipe),
  resamples = cv_resamples
)

# Collect metrics
metrics <- collect_metrics(glm_fit_results)
print(metrics)
```




